language: objective-c
script:
  - xctool -workspace Ladoga.xcworkspace -scheme Ladoga -sdk macosx ONLY_ACTIVE_ARCH=NO
  - xctool test -workspace Ladoga.xcworkspace -scheme Ladoga -sdk macosx ONLY_ACTIVE_ARCH=NO
  - xctool -workspace Ladoga.xcworkspace -scheme Ladoga -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool test -workspace Ladoga.xcworkspace -scheme Ladoga -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
